### PR TITLE
stringsAsFactor Bug.

### LINKED ISSUE #343: CRAN error (possibly vapply)
We're erroring on CRAN on several different OS's (see https://cran.r-project.org/web/checks/check_results_estimatr.html). The error from R CMD CHECK is this:

```
#> ERROR
7092#> Running the tests in ‘tests/testthat.R’ failed.
7093#> Last 13 lines of output:
7094#> ── 1. Error: FE matches lm_robust with one block (@test-lm-robust-fes.R#528) ──
7095#> contrasts can be applied only to factors with 2 or more levels
7096#> Backtrace:
7097#> 1. estimatr::lm_robust(...)
7098#> 2. estimatr::lm_robust_fit(...)
7099#> 3. estimatr:::prep_data(...)
7100#> 5. stats::model.matrix.default(~0 + ., data = fe_dat)
7101#> 6. stats::`contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])
```

We have traced the error to the creation of the switch `any(fe_levels == 1)` through this code:

```
  if (fes) {
    fe_dat <- as.data.frame(data[["fixed_effects"]])
    fe_levels <- vapply(fe_dat, nlevels, 0L)
    if (any(fe_levels == 1)) {
```

This may be related to multiple changes in R 3.6.3 in `vapply`. We can't reproduce the error because it is on the devel version of R only on linux and it doesn't affect release which we did get to work.

Any thoughts appreciated @nfultz @lukesonnet or others!

### PR DESCRIPTION
**Pull request by nfultz**
closes #343

### CODE REVIEW

**Comment by nfultz** [comment]
Also, the build is now pulling in ~50 dependencies, and takes > 20m to run. I recommend pruning old things if possible.

**Comment by graemeblair** [comment]
This says closes #343 do you think they are related?

**Comment by nfultz** [comment]
Yes

**Comment by graemeblair** [comment]
Sorry, see how they are related now :) Thanks Neal!

**Pull request merged**
