### PR TITLE
change reference names in glance.iv_robust

### PR DESCRIPTION
**Pull request by Gedevan-Aleksizde**
for issue #385

### CODE REVIEW

**Comment by nfultz** [comment]
Thank you for your contribution and for your patience.  If you have some more time, could you also write a test for the new names?

**Comment by Gedevan-Aleksizde** [comment]
OK. But could you tell me test guidelines more? I will write only write the test whether the output column is  `NA` or not in `test-iv-robust.R`. Is it enough?

**Comment by Gedevan-Aleksizde** [comment]
How about this? I wrote the test in `test_that("tidy, glance, summary, and print work", ...` in `test-S3-methods.R`

**Comment by nfultz** [comment]
It looks good to me, thanks. @lukesonnet ?

**Comment by lukesonnet** [comment]
Oof, sorry for this bug! Thanks for landing a fix and the tests! Looks good to me.

**Review by lukesonnet — APPROVED** [review]

**Pull request merged**
