### PR TITLE
add modelsummary to tests, regression table vignette, and DESCRIPTION

### PR DESCRIPTION
**Pull request by vincentarelbundock**
This PR supersedes this WIP: https://github.com/DeclareDesign/estimatr/pull/326

`modelsummary` and `gt` are now on CRAN, so we can add a test and a note in the vignette.

The test raises a warning because some of the `estimatr` objects do not have an associated `nobs` method. I could try to put one together in a separate PR if you think that's useful.

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
Also, I put `modelsummary` just after `texreg` in the vignette. This is perhaps presumptuous, but I figured that those are the only 2 packages that work out-of-the-box without hacks. Let me know if I should re-order.

**Comment by nfultz** [comment]
LGTM, :+1:

**Comment by vincentarelbundock** [comment]
Both of my PRs (#346 and #347) used to fail on Travis. Sorry it took me so long to get back to them!

Turns out there was nothing wrong with the code. I just merged upstream master and all the checks are now green.

[this post is copied in both PRs]

**Comment by vincentarelbundock** [comment]
thanks a lot for the merge. changes will appear on the website next time `pkgdown` is deployed.

**Pull request merged**
