### PR TITLE
VIgnette skeleton; S3 methods

### PR DESCRIPTION
**Pull request by lukesonnet**
Adds a skeleton of the vignette, building out citations and sources for the different options we provide. #10 

Also builds out the S3 methods to include coef, confint, summary, and print. #28

### CODE REVIEW

**Comment by graemeblair** [comment]
Thanks Luke. Will wait to merge until the tests pass, I assume?

**Comment by lukesonnet** [comment]
They pass. It's the same error looking for `obtain_permutation_matrix` from randomizr. There is also a warning about non-ascii characters but I'd rather resolve that when we push to CRAN as that'll just take one pass through all the code.

**Comment by graemeblair** [comment]
Got it. I assume that you've tested it with the Github version of randomizr and it works so merging in.

**Comment by lukesonnet** [comment]
It passes tests on my local machine with randomizr installed in the last week from github.

**Pull request merged**
