### PR TITLE
Tidyverse vignette

### PR DESCRIPTION
**Pull request by acoppock**
please accept my vignette

### CODE REVIEW

**Comment by acoppock** [comment]
Also just added a regression tables vignette

**Comment by nfultz** [comment]
@lukesonnet can you pull this in and close it before you ship 0.8

**Comment by lukesonnet** [comment]
I wasn't going to because we don't actually ship any vignettes to CRAN.

**Comment by lukesonnet** [comment]
In addition to Alex's two new vignettes (which I edited a little), I added a fixed effects vignette, updated the speed comparisons, changed the front page substantially, and restructured the menus.

This also adds the new functions and man pages changes to the website.

**Pull request merged**
